# Generated by Django 4.2.5 on 2023-09-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfile',
            name='file',
            field=models.FileField(db_index=True, upload_to='C:\\Dev\\picasso\\picasso\\app\\files'),
        ),
    ]
